services:
    # Servicio Backend (Laravel)
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            # Cambiamos el puerto para que la API responda en el 8000
            - '8000:80'
            # - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on: {  }

    # Servicio para el Frontend (Puerto 8080)
    frontend:
        image: 'nginx:alpine'
        ports:
            - '8080:80'
        volumes:
            # Mapear carpeta root/frontend al contenedor de Nginx
            # Asumiendo que 'compose.yaml' est√° en root/backend
            - '../frontend:/usr/share/nginx/html'
        networks:
            - sail

networks:
    sail:
        driver: bridge
