services:
    # Servicio Backend (Laravel)
    laravel.test:
        build:
            # Apuntar a la carpeta manual
            context: './docker/8.5'
            # context: './vendor/laravel/sail/runtimes/8.5' --- IGNORE ---
            dockerfile: Dockerfile
            args:
                # El ":-1000" es el truco para que no de error si no existe la variable
                WWWGROUP: '${WWWGROUP:-1000}'
        image: 'sail-8.5/app'
        # Usamos command para ejecutar nuestro setup y luego el servidor
        command: /bin/sh -c "/var/www/html/docker-entrypoint.sh && php artisan serve --host=0.0.0.0 --port=80"
        # Sobrescribimos el comando para ejecutar nuestro script antes de iniciar
        # entrypoint: ['/var/www/html/docker-entrypoint.sh', 'php', 'artisan', 'serve', '--host=0.0.0.0', '--port=80']
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            # Cambiamos el puerto para que la API responda en el 8000
            - '8000:80'
            # - '${APP_PORT:-80}:80'    --- IGNORE ---
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            WWWGROUP: '${WWWGROUP:-1000}'
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on: {  }

    # Servicio para el Frontend (Puerto 8080)
    frontend:
        image: 'nginx:alpine'
        ports:
            - '8080:80'
        volumes:
            # Mapear carpeta root/frontend al contenedor de Nginx
            # Asumiendo que 'compose.yaml' est√° en root/backend
            - '../frontend:/usr/share/nginx/html'
        networks:
            - sail

networks:
    sail:
        driver: bridge
